output_filename: test.jsonl # output path
output_dir: ./data/
#output_path: /persistentshare/storage/team_nakamura/yamaguchi/data/text/0313wiki.jsonl
#output_path: /persistentshare/storage/team_nakamura/yamaguchi/data/text/0313wiki_1000000.jsonl
#max_records: 600000 #1 datasetあたりの最大件数｡debug時は小さくする
#max_records: 10000 #1 datasetあたりの最大件数｡debug時は小さくする
max_records: 10 #1 datasetあたりの最大件数｡debug時は小さくする
#max_records: 100000 #1 datasetあたりの最大件数｡debug時は小さくする
overwrite: True # output_pathを上書きする
continue_process: False